INSERT INTO users (id, first_name, last_name, email)
VALUES (
        1,
        'Alice',
        'Johnson',
        'alice.johnson@example.com'
    ),
    (
        2,
        'Bob',
        'Smith',
        'bob.smith@example.com'
    ),
    (
        3,
        'Charlie',
        'Williams',
        'charlie.williams@example.com'
    ),
    (
        4,
        'Diana',
        'Brown',
        'diana.brown@example.com'
    ),
    (
        5,
        'Ethan',
        'Jones',
        'ethan.jones@example.com'
    ),
    (
        6,
        'Fiona',
        'Garcia',
        'fiona.garcia@example.com'
    ),
    (
        7,
        'George',
        'Martinez',
        'george.martinez@example.com'
    ),
    (
        8,
        'Hannah',
        'Lee',
        'hannah.lee@example.com'
    ),
    (
        9,
        'Ivan',
        'Walker',
        'ivan.walker@example.com'
    ),
    (
        10,
        'Julia',
        'Hall',
        'julia.hall@example.com'
    );